### ISSUE TITLE
ember-cli-cordova-auth with phonegap-facebook-connect plugin

### ISSUE THREAD

**Issue by bluegod** [poetic/ember-cli-cordova-auth#8]
I'm trying to show a popup using the signInWithFacebook function, passing an array of permissions. However when I test this in the simulator (ios and android) nothing pops up and there is no error message whatsoever.

Do you have an idea what could have gone wrong?

As I don't see much activity here (or any actual examples) is the project still active/maintained?

**Comment by DanyHunter** [comment]
bluegod, 

It looks like our documentation is not very clear. I'll go ahead and build an example app using this connect plugin. 

As for your issue, I just built a simple test ember app that uses FB login and it is working. A few things to note:
- the FB plugin needs to be added to your project by cloning [the plugin](https://github.com/Wizcorp/phonegap-facebook-plugin), going to the cordova dir of the project and using `cordova plugins add ~/path/to/the/plugin` otherwise it may not work. 
- You can see more debug information if you enable safari inspector to work on the simulator. If you have the inspector open when using the simulator you may get a glimpse of the error that is causing it not to work for you. 

Here is an example of login with FB:
```
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    signInFb: function() {
      this.session.signInWithFacebook(['public_profile', 'email']).then(function(ret) {
        console.log(ret);
      }, function(error) {
        alert('there was an error using fb login');
        console.log(error);
      });
    }
  }
});
```
This should be enough to get you going. Let me know if you are still having difficulties.

**Comment by bluegod** [comment]
Thanks @DanyHunter 

I did add the plugin locally after cloning the repo - this was also stated in the readme.

I have tried your code and enabled the safari inspector. I get an exception thrown ( I see the alert) and in the inspector I can see "Facebook login only available in app". Any idea why is that the case?

**Comment by DanyHunter** [comment]
Well, that error happens when variable `facebookConnectPlugin` does not exist. Are you using [ember-cli-cordova](https://github.com/poetic/ember-cli-cordova)? It looks like the js for the plugin is not loaded. 

Do you get any other errors on the console when the app first boots? You can figure that out by calling `window.location.reload()` on the safari console with the simulator running.

**Comment by bluegod** [comment]
Yes, I'm using ember-cli-cordoba. I do get an error after reloading the app:

Failed to load resource: The requested URL was not found on this server: file:///ember-cli-live-reload.js

Do we need to manually import the JS for the plugin?

My NPM dependencies look like this:

```javascript 
"devDependencies": {
    "animate.css": "^3.1.1",
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "broccoli-sass": "^0.3.3",
    "ember-cli": "0.1.5",
    "ember-cli-content-security-policy": "git://github.com/rwjblue/ember-cli-content-security-policy.git#master",
    "ember-cli-cordova": "0.0.15",
    "ember-cli-cordova-auth": "^0.1.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-esnext": "0.1.1",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-pure": "^0.1.0",
    "ember-cli-qunit": "0.1.2",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "liquid-fire": "^0.16.0"
  }
```
and I have the fb plugin installed on: cordova/plugins/com.phonegap.plugins.facebookconnect/

I don't think I actually followed the setup for this plugin though, as I assumed it was being imported/used by ember-cli-cordova-auth. For instance I haven't added a `<div id="fb-root"></div>`

**Comment by DanyHunter** [comment]
I think I've seen that before, can you copy/paste your config/environment.js file?

**Comment by bluegod** [comment]
Yup: https://pastee.org/ek7c

I'm happy to screenhero / skype / hangouts / teamviewer you so you can check out our code...

**Comment by DanyHunter** [comment]
I can't sign in to to screenhero but you can invite me (daniel at poetic systems com).

**Comment by bluegod** [comment]
The change to cordova.rebuildOnChange solved the 'ember-cli-live-reload.js' issue - not sure if this affects live reload?

However the main problem is still there.

PS I have invited you to screenhero.

**Comment by DanyHunter** [comment]
Closing this issue since we figured it out. The first time the FBPlugin was added it did not correctly set up the `.h`, `.m` and `js` files in the project.

**Comment by eliezerdt** [comment]
Hello @DanyHunter, i have the same problem, what are the steps to configure the .h, .m and js files?

**Comment by DanyHunter** [comment]
We solved it by re-adding the plugin to the cordova project. Instructions on how to set it up for ios are here: https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/ios/README.md and for android here: https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/android/README.md

The gist of it is: 

1. Clone down phonegap-facebook-plugin
2. use [cordova cli](https://github.com/apache/cordova-cli/) to `cordova plugins add /path/to/plugin  --variable APP_ID="123456789" --variable APP_NAME="myApplication"`
3. that should do the trick.
